"""HTML output — generates a self-contained, shareable news digest page."""
import html
from typing import List
from clawler.models import Article


class HTMLFormatter:
    def format(self, articles: List[Article]) -> str:
        rows = []
        for i, a in enumerate(articles, 1):
            ts = html.escape(a.timestamp.strftime("%Y-%m-%d %H:%M UTC")) if a.timestamp else "—"
            title = html.escape(a.title)
            url = html.escape(a.url)
            source = html.escape(a.source)
            summary = html.escape(a.summary[:200]) if a.summary else ""
            category = html.escape(a.category)
            summary_html = f'<p class="summary">{summary}</p>' if summary else ""
            rows.append(
                f'<article class="story">'
                f'<h3>{i}. <a href="{url}" target="_blank" rel="noopener">{title}</a></h3>'
                f'<div class="meta">'
                f'<span class="source">📰 {source}</span>'
                f'<span class="time">🕐 {ts}</span>'
                f'<span class="cat">🏷️ {category}</span>'
                f'</div>'
                f'{summary_html}'
                f'</article>'
            )

        body = "\n".join(rows)
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Clawler News Digest — {len(articles)} stories</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 800px; margin: 2rem auto; padding: 0 1rem; background: #0d1117; color: #c9d1d9; }}
  h1 {{ color: #58a6ff; }}
  a {{ color: #58a6ff; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .story {{ border-bottom: 1px solid #21262d; padding: 1rem 0; }}
  .story h3 {{ margin: 0 0 0.3rem; font-size: 1.05rem; }}
  .meta {{ font-size: 0.85rem; color: #8b949e; display: flex; gap: 1rem; flex-wrap: wrap; }}
  .summary {{ font-size: 0.9rem; color: #8b949e; margin: 0.4rem 0 0; }}
</style>
</head>
<body>
<h1>🗞️ Clawler News Digest</h1>
<p>{len(articles)} stories</p>
{body}
<footer style="margin-top:2rem;color:#484f58;font-size:0.8rem">Generated by <a href="https://github.com/clawdiard/clawler">Clawler</a></footer>
</body>
</html>"""
